[package]
name = "race_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
termion = "4.0.3"
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
